
default: &default
  # adapter: mysql2
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: root
  host: 127.0.0.1
  port: 5432
  ##socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: webdevpro_development

test:
  <<: *default
  database: webdevpro_test

production:
  <<: *default
  database: webdevpro_production
  username: webdevpro
  password: <%= ENV['WEBDEVPRO_DATABASE_PASSWORD'] %>
