# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2569f49c2d855021b22ea68c06649b462ad8755efaf6238e75d45de27b95f7eb834f2da46751de87a2a72552a6586ababe6f32586ededb64f4a76d106061a8e7

test:
  secret_key_base: 2acca57400325215936a2e42617c739e2e599bf19d38a92fd519dda8c67ef862e3d04a9117267df5a96963d97c4782defee058a4b909cbb1a7d31f1cd615671c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
